version: '3.8'
services:
    postgres:
      image: "postgres"
      container_name: postgres_db
      ports:
      - "5432:5432"
      volumes:
      - postgres_volume:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: postgres_db
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 5s
        timeout: 10s
        retries: 5

    node_backend:
      build: .
      image: "node_backend"
      container_name: node_app
      ports:
      - "5000:5000"
      depends_on:
        postgres:
          condition: service_healthy
      environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - GEMINI_API_KEY=${GEMINI_API_KEY}

volumes:
  postgres_volume: